### PR TITLE
fix: toString should stringify node

### LINKED ISSUE #72: String(node) should produce string or throw more helpful error
### Expected Behavior / Situation

In postcss-values-parser v2, `String(node)` returns the string value of any `Node`. In postcss-values-parser v3, one must now use the `nodeToString` function to retrieve the string value. Worse yet, when a node is accidentally `toString`’d, an error is thrown!

I would prefers things work the same as they did in v2, as well as how they still do in PostCSS.

```js
const ast = parse('#000 url(path/to/image.jpg)');

console.log(String(ast)); // "#000 url(path/to/image.jpg)"
console.log(String(ast.nodes[0])); // "#000"
```

And here is an example of the stringified behavior currently in PostCSS:

```js
import postcss from 'postcss';

const ast = postcss.parse('selector { property-name: property-value; }');

console.log(String(ast.nodes[0].nodes[0])); // "property-name: property-value"
```

### Actual Behavior / Situation

```
TypeError: this[node.type] is not a function
```

### Modification Proposal

Remove the `TypeError: this[node.type] is not a function` error and default `toString` to work like `nodeToString`.

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [x] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

Fixes #72. Using `toString` or `String(node)` is failing due to the base PostCSS stringifier not being able to recognize our node types.

This isn't as elegant as I'd like, and does involve some code duplication that I'm not a fan of, but it gets the job done for the time being.

### CODE REVIEW

**Comment by shellscape** [comment]
@jonathantneal @jwilsson went back over the PR today and found that the tests for `toString()` weren't actually testing the node's `toString` - a copy/pasted typo was just checking a string against it's own toString.

That led me to refactor quite a bit, and revealed several subsequent shortcomings, all of which should now be fixed. I've improved the tests and coverage to guard against what I found moving forward. Please review again.

File: lib/index.js [hunk 1]
```diff
@@ -22,13 +20,24 @@ module.exports = {
...
+    root.toString = toString.bind(root);
+
     return parser.root;
   },
 
-  stringify(node, builder) {
-    const stringifier = new Stringifier(builder);
-    stringifier.stringify(node);
-  },
+  // stringify(node, builder) {
```
Comment (jonathantneal) [inline lib/index.js]: Should you remove this commented code if it has been replaced?

Comment (shellscape) [reply lib/index.js]: indeed. thanks for pointing that out
